events {}

http {
    upstream katalog {
        server service-katalog:8000;
    }

    upstream penawaran {
        server service-penawaran:8000;
    }

    upstream winner {
        server service-winner:8000;
    }

    server {
        listen 80;

        # Katalog Service
        location /katalog/ {
            rewrite ^/katalog/(.*)$ /$1 break;
            proxy_pass http://katalog;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Penawaran Service
        location /penawaran/ {
            rewrite ^/penawaran/(.*)$ /$1 break;
            proxy_pass http://penawaran;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Winner Service
        location /winner/ {
            rewrite ^/winner/(.*)$ /$1 break;
            proxy_pass http://winner;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Health check gateway
        location /health {
            return 200 '{"status":"ok","gateway":"TEAM-02"}';
            add_header Content-Type application/json;
        }
    }
}